Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IndustryIncident.Models;
using IndustryIncident.Models.ViewModels;
using System.Data.Entity;
using Microsoft.AspNetCore.Authorization;

namespace IndustryIncident.Controllers
{
    [Authorize]

    public class UsersController : Controller
    {
        private readonly IndustryIncidentContext _context;

        public UsersController(IndustryIncidentContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            if (!this.User.IsInRole("Admin"))
            {
                return RedirectToAction("index", "notfound");

            }
            var listUser = _context.Users.ToList();

            var listViewModel = new List<UserViewModel>();
            foreach (var user in listUser)
            {
                var acces = from userAccess in _context.UserAcces
                            join zone in _context.Zones on userAccess.Idzone equals zone.Id
                            join u in _context.Users on userAccess.Iduser equals u.Id
                            where u.Id == user.Id
                            select zone;
                var role = from userRole in _context.UserRoles
                           join r in _context.Roles on userRole.Idrole equals r.Id
                           join u in _context.Users on userRole.Iduser equals u.Id
                           where u.Id == user.Id

                           select r;
                listViewModel.Add(new UserViewModel()
                {
                    Acces = acces.FirstOrDefault(),
                    Role = role.FirstOrDefault(),
                    Title = user.Title,
                    Name = user.Name,
                    FamillyName = user.FamillyName,
                    Id = user.Id
                });
            }
            return View(listViewModel);
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (!this.User.IsInRole("Admin"))
            {
                return RedirectToAction("index", "notfound");

            }
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = _context.Users
                .FirstOrDefault(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            var acces = from userAccess in _context.UserAcces
                        join zone in _context.Zones on userAccess.Idzone equals zone.Id
                        join u in _context.Users on userAccess.Iduser equals u.Id
                        where u.Id == user.Id
                        select zone;
            var role = from userRole in _context.UserRoles
                       join r in _context.Roles on userRole.Idrole equals r.Id
                       join u in _context.Users on userRole.Iduser equals u.Id
                       where u.Id == user.Id
                       select r;
            var listViewModel = new UserViewModel()
            {
                Acces = acces.FirstOrDefault(),
                Role = role.FirstOrDefault(),
                Title = user.Title,
                Name = user.Name,
                FamillyName = user.FamillyName,
                Id = user.Id
            };
            return View(listViewModel);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            if (!this.User.IsInRole("Admin"))
            {
                return RedirectToAction("index", "notfound");

            }
            ViewData["Role"] = new SelectList(_context.Roles, "Id", "Role1");
            ViewData["Zone"] = new SelectList(_context.Zones, "Id", "Name");
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,FamillyName,Title,AccesID,RoleID")] UserViewModel userViewModel)
        {
            ModelState.Remove("Role.Role1");
            ModelState.Remove("Acces.Name");
            if (ModelState.IsValid)
            {
                var user = new User()
                {
                    Id = userViewModel.Id,
                    FamillyName = userViewModel.FamillyName,
                    Name = userViewModel.Name,
                    Title = userViewModel.Title
                };
                var userRole = new UserRole()
                {
                    Iduser = user.Id,
                    Idrole = userViewModel.RoleID
                };
                var userAcces = new UserAcce()
                {
                    Iduser = user.Id,
                    Idzone = userViewModel.AccesID
                };
                _context.Add(user);
                _context.Add(userAcces);
                _context.Add(userRole);
                await _context.SaveChangesAsync();
                ViewData["Role"] = new SelectList(_context.Roles, "Id", "Role1", userViewModel.RoleID);
                ViewData["Zone"] = new SelectList(_context.Zones, "Id", "Name", userViewModel.AccesID);
                return RedirectToAction(nameof(Index));
            }
            return View(userViewModel);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (!this.User.IsInRole("Admin"))
            {
                return RedirectToAction("index", "notfound");

            }
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var acces = from userAccess in _context.UserAcces
                        join zone in _context.Zones on userAccess.Idzone equals zone.Id
                        join u in _context.Users on userAccess.Iduser equals u.Id
                        where u.Id == user.Id
                        select zone;
            var role = from userRole in _context.UserRoles
                       join r in _context.Roles on userRole.Idrole equals r.Id
                       join u in _context.Users on userRole.Iduser equals u.Id
                       where u.Id == user.Id
                       select r;
            var userViewModel = new UserViewModel()
            {
                Acces = acces.FirstOrDefault(),
                Role = role.FirstOrDefault(),
                Title = user.Title,
                Name = user.Name,
                FamillyName = user.FamillyName,
                Id = user.Id,
                AccesID = acces.FirstOrDefault().Id,
                RoleID = role.FirstOrDefault().Id
            };
            ViewData["Role"] = new SelectList(_context.Roles, "Id", "Role1", userViewModel.RoleID);
            ViewData["Zone"] = new SelectList(_context.Zones, "Id", "Name", userViewModel.AccesID);

            return View(userViewModel);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,FamillyName,Title,AccesID,RoleID")] UserViewModel userViewModel)
        {
            ModelState.Remove("Role.Role1");
            ModelState.Remove("Acces.Name");
            if (id != userViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var user = new User()
                    {
                        Id = userViewModel.Id,
                        FamillyName = userViewModel.FamillyName,
                        Name = userViewModel.Name,
                        Title = userViewModel.Title
                    };
                    var userRole = new UserRole()
                    {
                        Iduser = user.Id,
                        Idrole = userViewModel.RoleID
                    };
                    var userAcces = new UserAcce()
                    {
                        Iduser = user.Id,
                        Idzone = userViewModel.AccesID
                    };
                    var currentRole = _context.UserAcces.FirstOrDefault(x => x.Iduser == user.Id);
                    var currentAcces = _context.UserRoles.FirstOrDefault(x => x.Iduser == user.Id);
                    if (currentRole != null) _context.Remove(currentRole);
                    if (currentAcces != null) _context.Remove(currentAcces);
                    await _context.SaveChangesAsync();
                    _context.Update(user);
                    _context.Add(userAcces);
                    _context.Add(userRole);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(userViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Role"] = new SelectList(_context.Roles, "Id", "Role1", userViewModel.RoleID);

Controllers/ZonesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IndustryIncident.Models;
using Microsoft.AspNetCore.Authorization;

namespace IndustryIncident.Controllers
{
    [Authorize]

    public class ZonesController : Controller
    {
        private readonly IndustryIncidentContext _context;

        public ZonesController(IndustryIncidentContext context)
        {
            _context = context;
        }

        // GET: Zones
        public async Task<IActionResult> Index()
        {
            if (!this.User.IsInRole("Admin"))
            {
                return RedirectToAction("index", "notfound");

            }
            return View(await _context.Zones.ToListAsync());
        }

        // GET: Zones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!this.User.IsInRole("Admin"))
            {
                return RedirectToAction("index", "notfound");

            }
            if (id == null || _context.Zones == null)
            {
                return NotFound();
            }

            var zone = await _context.Zones
                .FirstOrDefaultAsync(m => m.Id == id);
            if (zone == null)
            {
                return NotFound();
            }

            return View(zone);
        }

        // GET: Zones/Create
        public IActionResult Create()
        {
            if (!this.User.IsInRole("Admin"))
            {
                return RedirectToAction("index", "notfound");

            }
            return View();
        }

        // POST: Zones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Zone zone)
        {
            if (ModelState.IsValid)
            {
                _context.Add(zone);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(zone);
        }

        // GET: Zones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!this.User.IsInRole("Admin"))
            {
                return RedirectToAction("index", "notfound");

            }
            if (id == null || _context.Zones == null)
            {
                return NotFound();
            }

            var zone = await _context.Zones.FindAsync(id);
            if (zone == null)
            {
                return NotFound();
            }
            return View(zone);
        }

        // POST: Zones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Zone zone)
        {
            if (id != zone.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(zone);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ZoneExists(zone.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(zone);
        }

        // GET: Zones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (_context.Zones == null)
            {
                return Problem("Entity set 'IndustryIncidentContext.Zones'  is null.");
            }
            var zone = await _context.Zones.FindAsync(id);
            if (zone != null)
            {
                _context.Zones.Remove(zone);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // POST: Zones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Zones == null)
            {
                return Problem("Entity set 'IndustryIncidentContext.Zones'  is null.");
            }
            var zone = await _context.Zones.FindAsync(id);
            if (zone != null)
            {
                _context.Zones.Remove(zone);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ZoneExists(int id)
        {
          return _context.Zones.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IndustryIncident</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IndustryIncident.styles.css" asp-append-version="true" />
    <style>
        a{
            color:white;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto col-md-2 col-xl-2 px-sm-2 px-0 bg-dark">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline">
                            <span style="font-size: 45px;color: green;font-weight: 800;">S</span>
                            <span style ="font-size: 45px;color: red;font-weight: 800;">Q</span>
                            <span style="font-size: 45px;color: grey;font-weight: 800;">C</span>
                            <span style="font-size: 45px;color: aqua;font-weight: 800;">D</span>
                            <span style="font-size: 45px;color: orange;font-weight: 800;">M</span>
                        </span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        <li class="nav-item"style="color:white;margin: 20%;">
                            <a style="color:white;" class="navbar-link" asp-area="" asp-controller="Incidents" asp-action="Index">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                            </a>
                        </li>
                       @if( @User.IsInRole("Admin")){
                            <li style ="color:white;margin: 20%;">
                                <a style="color:white" href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Administration</span>
                            </a>
                            <ul class="collapse nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                                <li class="w-100">
                                    <a style="color:white;" asp-area="" asp-controller="Users" asp-action="Index" class="nav-link px-0"> <span class="d-none d-sm-inline">User</span>  </a>
                                </li>
                                <li class="w-100">
                                    <a style ="color:white;" asp-area="" asp-controller="Zones" asp-action="Index" class="nav-link px-0"> <span class="d-none d-sm-inline">Zone</span> </a>
                                </li>
                                <li class="w-100">
                                    <a style="color:white;" asp-area="" asp-controller="Indicators" asp-action="Index" class="nav-link px-0"> <span class="d-none d-sm-inline">Indicator</span> </a>
                                </li>
                                <li class="w-100">
                                    <a style="color:white;" asp-area="" asp-controller="IncidentTypes" asp-action="Index" class="nav-link px-0"> <span class="d-none d-sm-inline">Type</span> </a>
                                </li>
                            </ul>
                        </li>
                        }
                       
                    </ul>
                    <hr>
                    <div class="pb-4"><span>
                            <img src="~/img/User_Avatar.png" alt="hugenerd" width="30" height="30" class="rounded-circle">
                            <span class="d-none d-sm-inline mx-1">Hello, @User.Identity?.Name!</span>
@*                        <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                            <li><a class="dropdown-item" href="#">New project...</a></li>
                            <li><a class="dropdown-item" href="#">Settings</a></li>
                            <li><a class="dropdown-item" href="#">Profile</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Sign out</a></li>
                        </ul>*@
                        </span>
                    </div>
                </div>
            </div>
            <div class="col py-3">
            @RenderBody()
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link href="~/css/froms.css" rel="stylesheet" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>